### ISSUE TITLE
Figure out how to integrate google calendar

### ISSUE THREAD

**Issue by readysetagile** [FCCColumbus/cbus-web#37]
Need a way to for the general public to access the TechLife Columbus calendar without logging in

**Comment by readysetagile** [comment]
_From Discord:_ 
Hi all.  I'm seeking solutions from our wealth of technologists. 🙂 

meetup.com has recently locked public access to all group calendars.  This means that you must be logged into meetup.com to see a community calendar of events (like TechLife Columbus and Free Code Camp). 

Normally this does not matter to you and I as individuals.  However, the "geniuses" at meetup failed to realize that you cannot "subscribe" to the calendars using a URL anymore (to my knowledge there is no "login" functionality with calendar subscriptions).  The only way you can stay up-to-date with meetup groups is to 1) view the calendar on their website, or 2) export  the .ics file and import it yourself periodically into your calendar of choice.

What's more is that this is intended functionality for some unknown reason (no update either), and meetup is not taking feedback (see my support request https://help.meetup.com/hc/en-us/requests/1409377).

So - being the hacker that I am - I am  seeking a workaround.  How can we automate this process?  I want a way for the general public to access the TechLife Columbus calendar without logging in.  Keep in mind that Free Code Camp Columbus does have a Google account, so creating an App Script would be the preferred solution -- but I am tech agnostic.

**Comment by readysetagile** [comment]
I found a workaround to getting an ICS from meetup without logging in, but you still need an account to get a member ID, and this member ID is used in a call to set the headers in an HTTP request.  

Next steps are to get a meetup.com account for the Free Code Camp users, and use this to create a shared calendar for the FCC google account.  We can then write integration code into the React website to access that calendar

**Comment by jduffey** [comment]
This is as far as I got last month when I started poking around at this: https://gist.github.com/jduffey/add9321813ba57bf1f5247ed3157a1e2

Without an API for this I think it's going to be a very fragile implementation to get something up that's actually reliable over the long term.

**Comment by readysetagile** [comment]
I created a google app script that reads the TechLife Columbus calendar and creates an .ics file that is stored in the Free Code Camp Columbus Google Drive.  the script executes daily early in the morning.

The result .ics file is [here](https://drive.google.com/file/d/15CscXC8lA0vGlAn9ZxjCX8628f0wStX24wK1DhbxBu4/view?usp=sharing).

Next steps are to create an integration in the FCC Columbus website to consume this .ics file and render it to a web component
